version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.8
    environment:
      RABBITMQ_HOST: 'rabbitmq'
      RABBITMQ_DEFAULT_USER: 'rabbit_user'
      RABBITMQ_DEFAULT_PASS: '1234'
    ports:
      - "5672:5672"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'task_db'
    volumes:
      - ./mariadb:/var/lib/mysql

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/app
    ports:
      - "9000:9000"
    depends_on:
      - rabbitmq
      - mariadb
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1

  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
    environment:
      CLICKHOUSE_HOST: 'clickhouse'
      CLICKHOUSE_DB: 'clickhouse'
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD:
    volumes:
      - ./clickhouse:/var/lib/clickhouse
networks:
  mynetwork:
    driver: bridge